package com.pitchplayer.stats.om;
// Generated Oct 21, 2007 12:24:53 PM by Hibernate Tools 3.2.0.b11



/**
 * GamePlayerId generated by hbm2java
 */
public class GamePlayerId  implements java.io.Serializable {


     private int gameId;
     private int userId;

    public GamePlayerId() {
    }

    public GamePlayerId(int gameId, int userId) {
       this.gameId = gameId;
       this.userId = userId;
    }
   
    public int getGameId() {
        return this.gameId;
    }
    
    public void setGameId(int gameId) {
        this.gameId = gameId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GamePlayerId) ) return false;
		 GamePlayerId castOther = ( GamePlayerId ) other; 
         
		 return (this.getGameId()==castOther.getGameId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGameId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


