package com.pitchplayer.stats.om;
// Generated Dec 13, 2007 7:54:01 PM by Hibernate Tools 3.2.0.b11


import com.pitchplayer.userprofiling.om.User;
import java.math.BigDecimal;

/**
 * PlayerStat generated by hbm2java
 */
public class PlayerStat  implements java.io.Serializable, Comparable {

	/**
	 * indicates that a record represents a summary of multiple game types (e.g., singles + doubles)
	 */ 
	public static final byte COMBINED_GAME_TYPE = 0; 

	private int playerStatId;
	private Integer userId;
	private String username;
	private byte gameType;
	private Integer games;
	private Integer wins;
	private Integer losses;
	private Integer quits;
	private float winPct;

	public PlayerStat() {
	}


    public PlayerStat(int playerStatId, Integer userId, String username, byte gameType) {
        this.playerStatId = playerStatId;
        this.userId = userId;
        this.username = username;
        this.gameType = gameType;
    }
    public PlayerStat(int playerStatId, Integer userId, String username, byte gameType, Integer games, Integer wins, Integer losses, float winPct) {
       this.playerStatId = playerStatId;
       this.userId = userId;
       this.username = username;
       this.gameType = gameType;
       this.games = games;
       this.wins = wins;
       this.losses = losses;
       this.winPct = winPct;
    }
   
    public int getPlayerStatId() {
        return this.playerStatId;
    }
    
    public void setPlayerStatId(int playerStatId) {
        this.playerStatId = playerStatId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public byte getGameType() {
        return this.gameType;
    }
    
    public void setGameType(byte gameType) {
        this.gameType = gameType;
    }
    public Integer getGames() {
        return this.games;
    }
    
    public void setGames(Integer games) {
        this.games = games;
    }
    public Integer getWins() {
        return this.wins;
    }
    
    public void setWins(Integer wins) {
        this.wins = wins;
    }
    public Integer getLosses() {
        return this.losses;
    }
    
    public void setLosses(Integer losses) {
        this.losses = losses;
    }


	public Integer getUserId() {
		return userId;
	}


	public void setUserId(Integer userId) {
		this.userId = userId;
	}


	public float getWinPct() {
		return winPct;
	}


	public void setWinPct(float winPct) {
		this.winPct = winPct;
	}


	public int compareTo(Object obj) {
		PlayerStat other = (PlayerStat)obj;
		if (getWinPct() < other.getWinPct()) {
			return -1;
		}
		else if (getWinPct() > other.getWinPct()) {
			return 1;
		}
		else {
			return 0;
		}
	}


	public Integer getQuits() {
		return quits;
	}


	public void setQuits(Integer quits) {
		this.quits = quits;
	}




}


