package com.pitchplayer.userprofiling.om;
// Generated Dec 14, 2007 2:54:10 PM by Hibernate Tools 3.2.0.b11


import java.util.Date;

/**
 * UserInvitation generated by hbm2java
 */
public class UserInvitation  implements java.io.Serializable {


     private int invitationId;
     private User user;
     private String invitationCode;
     private String inviteeEmail;
     private byte status;
     private Date sentDate;

    public UserInvitation() {
    }

    public UserInvitation(User user, String invitationCode, String inviteeEmail, byte status, Date sentDate) {
       this.user = user;
       this.invitationCode = invitationCode;
       this.inviteeEmail = inviteeEmail;
       this.status = status;
       this.sentDate = sentDate;
    }
   
    public int getInvitationId() {
        return this.invitationId;
    }
    
    public void setInvitationId(int invitationId) {
        this.invitationId = invitationId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getInvitationCode() {
        return this.invitationCode;
    }
    
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode;
    }
    public String getInviteeEmail() {
        return this.inviteeEmail;
    }
    
    public void setInviteeEmail(String inviteeEmail) {
        this.inviteeEmail = inviteeEmail;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Date getSentDate() {
        return this.sentDate;
    }
    
    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }




}


