package com.pitchplayer.userprofiling.om;
// Generated Oct 21, 2007 12:24:53 PM by Hibernate Tools 3.2.0.b11



/**
 * UserHomeAddress generated by hbm2java
 */
public class UserHomeAddress  implements java.io.Serializable {


     private int userId;
     private User user;
     private String city;
     private String state;
     private String country;
     private String homePhone;
     private String mobilePhone;

    public UserHomeAddress() {
    }

	
    public UserHomeAddress(int userId, User user) {
        this.userId = userId;
        this.user = user;
    }
    public UserHomeAddress(int userId, User user, String city, String state, String country, String homePhone, String moblePhone) {
       this.userId = userId;
       this.user = user;
       this.city = city;
       this.state = state;
       this.country = country;
       this.homePhone = homePhone;
       this.mobilePhone = mobilePhone;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String moblePhone) {
        this.mobilePhone = mobilePhone;
    }




}


