package com.pitchplayer.userprofiling.om;
// Generated Dec 14, 2007 2:54:10 PM by Hibernate Tools 3.2.0.b11


import java.util.Date;

/**
 * UserAssociation generated by hbm2java
 */
public class UserAssociation  implements java.io.Serializable {


     private Integer userAssociationId;
     private User userByUserId;
     private User userByAssociateId;
     private byte associationType;
     private Date dateCreated;
     private Date dateAccepted;
     private int status;

     public static final int STATUS_CONFIRMED = 1;
     public static final int STATUS_REQUESTED = 0;

    public UserAssociation() {
    }

	
    public UserAssociation(User userByUserId, User userByAssociateId, byte associationType, Date dateCreated) {
        this.userByUserId = userByUserId;
        this.userByAssociateId = userByAssociateId;
        this.associationType = associationType;
        this.dateCreated = dateCreated;
    }
    public UserAssociation(User userByUserId, User userByAssociateId, byte associationType, Date dateCreated, Date dateAccepted, int status) {
       this.userByUserId = userByUserId;
       this.userByAssociateId = userByAssociateId;
       this.associationType = associationType;
       this.dateCreated = dateCreated;
       this.dateAccepted = dateAccepted;
       this.status = status;
    }
   
    public Integer getUserAssociationId() {
        return this.userAssociationId;
    }
    
    public void setUserAssociationId(Integer userAssociationId) {
        this.userAssociationId = userAssociationId;
    }
    public User getUserByUserId() {
        return this.userByUserId;
    }
    
    public void setUserByUserId(User userByUserId) {
        this.userByUserId = userByUserId;
    }
    public User getUserByAssociateId() {
        return this.userByAssociateId;
    }
    
    public void setUserByAssociateId(User userByAssociateId) {
        this.userByAssociateId = userByAssociateId;
    }
    public byte getAssociationType() {
        return this.associationType;
    }
    
    public void setAssociationType(byte associationType) {
        this.associationType = associationType;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateAccepted() {
        return this.dateAccepted;
    }
    
    public void setDateAccepted(Date dateAccepted) {
        this.dateAccepted = dateAccepted;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


